from classes import *
import os
spr_idle = Sprite(os.path.join("sprites", "idle.png"),150,150)
spr_walk = Sprite(os.path.join("sprites", "camarda walk.png"),150,150)
spr_jump = Sprite(os.path.join("sprites", "camarda jump.png"),150,150)
spr_punch = Sprite(os.path.join("sprites", "camarda jab.png"),150,150)
spr_mpunch = Sprite(os.path.join("sprites", "camarda m punch.png"),150,150)
spr_hpunch = Sprite(os.path.join("sprites", "camarda h punch.png"),150,150)
spr_lkick = Sprite(os.path.join("sprites", "camarda l kick.png"),150,150)
spr_mkick = Sprite(os.path.join("sprites", "camarda m kick.png"),150,150)
spr_hkick = Sprite(os.path.join("sprites", "camarda h kick.png"),150,150)
spr_cr = Sprite(os.path.join("sprites", "camarda crouch.png"),150,150)
spr_crjab = Sprite(os.path.join("sprites", "camarda crouch jab.png"),150,150)
spr_crmpunch = Sprite(os.path.join("sprites", "camarda crouch m punch.png"),150,150)
spr_crhpunch = Sprite(os.path.join("sprites", "camarda crouch h punch.png"),150,150)
spr_crmkick = Sprite(os.path.join("sprites", "camarda crouch m kick.png"),150,150)